// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv import removed for deployment environments where env vars are provided directly
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
